

0_OBJECTS	=	todo_api_0.c \
				todo_api_0.h

0_OUTPUT	=	todo_api_0

$(0_OUTPUT) : $(0_OBJECTS)
	gcc -o $@ $^




1_OBJECTS	=	todo_api_1.c \
				todo_api_1.h

1_OUTPUT	=	todo_api_1

$(1_OUTPUT) : $(1_OBJECTS)
	gcc -o $@ $^




2_OBJECTS	=	todo_api_2.c \
				todo_api_2.h

2_OUTPUT	=	todo_api_2

$(2_OUTPUT) : $(2_OBJECTS)
	gcc -o $@ $^




3_OBJECTS	=	todo_api_3.c \
				todo_api_3.h

3_OUTPUT	=	todo_api_3

$(3_OUTPUT) : $(3_OBJECTS)
	gcc -o $@ $^




4_OBJECTS	=	src-4/main.c \
				src-4/todo_api.h \
				src-4/post_todo_handler.c \
				src-4/list_ops.c

4_OUTPUT	=	todo_api_4

$(4_OUTPUT) : $(4_OBJECTS)
	gcc -g3 -o $@ $^

