

0_OBJECTS	=	todo_api_0.c \
				todo_api_0.h

0_OUTPUT	=	todo_api_0

$(0_OUTPUT) : $(0_OBJECTS)
	gcc -o $@ $^




1_OBJECTS	=	todo_api_1.c \
				todo_api_1.h

1_OUTPUT	=	todo_api_1

$(1_OUTPUT) : $(1_OBJECTS)
	gcc -o $@ $^
